spring:
  application:
    name: PGestionOne

  datasource:
    url: jdbc:mariadb://localhost:3310/pgestion_one
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: validate
  #      ddl-auto: validate #SOLO SE USA CON FLYWAY ACTIVO
  #      ddl-auto: update #SOLO SI NO SE ESTA USANDO FLYWAY
  flyway:
    enabled: true
    community-db-support-enabled: true # Se agrego por las versiones diferentes de Flyway y mariadb
    baseline-on-migrate: false #Solo se habilita por una vez para cuando se hace el esquema inicial, despues se quita
    baseline-version: 2
    locations: classpath:db/migration
